### ISSUE TITLE
Please add this script to test dir

### ISSUE THREAD

**Issue by GoogleCodeExporter** [alanv/tesseract-android-tools#33]
```
What steps will reproduce the problem?
1. On many device simulators, the install fails due to insufficient space when 
trying to run tesseract-android-tools-test.apk from eclipse.

What is the expected output? What do you see instead?
Test apk installed on device simulator, and run from eclipse.

What version of the product are you using? On what operating system?
Latest tesseract android tools based on tesseract 3.0.1/leptonica 1.68, Device 
simulator on MacOS, running tests on eclipse.

Please provide any additional information below.
I have prepared a script based on adb which pushes correct version of 
eng.traineddata and apk files to /mnt/sdcard on which more space can be 
allocated.

Please see attached files.
```

Original issue reported on code.google.com by `loni...@gmail.com` on 11 Mar 2012 at 4:31

Attachments:
- [run-tests](https://storage.googleapis.com/google-code-attachments/tesseract-android-tools/issue-33/comment-0/run-tests)
- [eng.traineddata](https://storage.googleapis.com/google-code-attachments/tesseract-android-tools/issue-33/comment-0/eng.traineddata)

**Comment by GoogleCodeExporter** [comment]
```
testGetUTF8Text failes because:
junit.framework.AssertionFailedError: "he\\o" != "hello"
at 
com.googlecode.tesseract.android.test.TessBaseAPITest.testGetUTF8Text(TessBaseAP
ITest.java:109)
at java.lang.reflect.Method.invokeNative(Native Method)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:169)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:154)
at 
android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:52
9)
at 
android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1448)

I'm wondering the accuacy of the eng.traineddata. Or,...is there something 
wrong?
```

Original comment by `xyxzfj@gmail.com` on 12 May 2012 at 5:14

**Comment by GoogleCodeExporter** [comment]
```
The test data same as whats there on the downloads section of tesseract page. I 
attached it just for convenience.

Which image are you attaching? Generated through test code or a camera snap?

```

Original comment by `loni...@gmail.com` on 12 May 2012 at 6:46

**Comment by GoogleCodeExporter** [comment]
Original comment by `alanv@google.com` on 11 Sep 2012 at 8:03
- Changed state: **Fixed**
